### ISSUE TITLE
Split up Internal Assistant into multiple smaller ones

### ISSUE THREAD

**Issue by jedrichards** [sketch-hq/sketch-assistant-internal#15]
Proposing the initial three Assistants as follows. Note I rolled the document organisation idea, and the dirty styles idea into the "Clean Up Assistant" - the separation was feeling a bit arbitrary to me since they're all very much "document hygiene" to me ...

#### Sketch Naming Conventions Assistant

> Defines naming conventions used by the Sketch design team

- Page names
  - Should start with an emoji, e.g. "♻Symbols"
- Artboard names
  - Should start with a numbering system e.g. "1.1 Splash screen"
- Group names
  - Not default value "Group"
- Symbol names
  - Must use the "/" based symbol organisation mechanic

#### Sketch Tidy Assistant

> Generalised document hygiene rules

- No disabled borders
- No disabled fills
- No disabled shadows
- No disabled inner shadows
- No hidden layers
- No unused shared styles
- No unused symbols
- No dirty layer styles
- No dirty text styles
- No empty groups
- No redundant groups
- No loose layers outside artboards
- Maximum layers in a group
  - Set max to 10
- Maximum ungrouped layers in an artboard
  - Set max to 5
- Subpixel positioning
  - Allow .5 increments only

#### Sketch Reuse Suggestions Assistant

> Notices when similar styles and groups could be abstracted into shared styles and symbols respectively

- Prefer shared layer styles
  - Tolerate 2 identical layer styles
- Prefer shared text styles
  - Tolerate 2 identical text styles
- Prefer symbols over groups
  - Tolerate 2 identical groups

> Based on https://www.notion.so/sketchapp/Assistants-Breakdown-dead30a0cf8d4ae6a417a7a377609f28

**Comment by christianklotz** [comment]
On the naming:

- **Naming Conventions:** perhaps better _Sketch Naming Conventions_? Or is already sufficiently communicated since it's going to be internal to Sketch anyway and release under own own org?
- **Clean Up:** does it sound too transactional, perhaps suggesting that it is _doing_ the clean up for you, I wonder 🤔, alternative suggestions: _Tidy_ (though similar issues as _Clean Up_ but maybe more positive), or something else more marketing speak that is more about "pointing out unpleasant things"?
- **Abstraction Suggestions:** _Reuse_, _Recycle_, _Recycling_, _Recycling Suggestions_

**Comment by prekesh** [comment]
Naming these isn't my strong point, but I like these! I guess my two suggestions would be to allow sub pixel increments of 0.25, 0.5, 0.75 and whole pixels. while .33 and .67 should be considered errors.

**Comment by christianklotz** [comment]
> sub pixel increments of 0.25, 0.5, 0.75 and whole pixels. while .33 and .67 should be considered errors.

The problem with this is that it tries to work around the missing ignore functionality, see https://github.com/sketch-hq/sketch-assistant-core-rules/pull/115#issuecomment-617270663.

**Comment by prekesh** [comment]
> > sub pixel increments of 0.25, 0.5, 0.75 and whole pixels. while .33 and .67 should be considered errors.
> 
> The problem with this is that it tries to work around the missing ignore functionality, see [sketch-hq/sketch-assistant-core-rules#115 (comment)](https://github.com/sketch-hq/sketch-assistant-core-rules/pull/115#issuecomment-617270663).

If this is for us to use, we should keep it at only 0.5 increments, and anything else is a violation. because that's what we use often. However we do also use 0.25 increments occasionally, in icons and certain UI elements (most of Apple's stuff is in 0.25 increments).

Perhaps in the future we can have extra pixel positioning rules that allow other values that could be used in other assistants.

**Comment by christianklotz** [comment]
As soon as you design for iPhone 11 Pro Max this is an issue however because the screens are using `3x`, hence `0.33` and `0.67`. I'm happy to set it to whatever is useful to us.

> However we do also use 0.25 increments occasionally

This is exactly the argument for an ignore mechanism, a hairline separator symbol for instance would be a one-in-x exception. As soon as you allow 0.25 it means I can place anything on quarters 🤔

**Comment by jedrichards** [comment]
Closing in favour of smaller tickets

- https://github.com/sketch-hq/sketch-assistants/issues/5
- https://github.com/sketch-hq/sketch-assistants/issues/4
- https://github.com/sketch-hq/sketch-assistants/issues/3
